language: java
jdk:
- openjdk11
sudo: false
install: true
script: mvn clean package -DskipTests=true
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: "-gladkih@starkovgrp.ru"
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN="e12ee89d-1f89-48af-8093-4b699c7ff59b"
deploy:
  provider: heroku
  api_key:
    secure: jB0lzm8kMjR7sFCEfzlFu5Oh57UIptISkVAOTXFcVt9P4JLFjFB1L9NqFXcbs4FvZAEnHerUtFoNaS3D4wjm5bgNxIneYt2IpoB2l2Skam+ylp2xa0xvajyVceEv936cdIiXlEi53c0p9V2TBq6NozAvn3bZkoto6/QJ8JkQMEN7JIwwuhZIf6Z2U3bYLoxGnti6LiFr0tMf42b1d+Leax06wLEbf3sYQS5nlMqhTJAvlZsnUqU3YVvya8fSUcYcOJmmXs7Bvb0CLOmQLyoLqVPGPr5wS2KekdAbP1W2RE9MyZ7N6fP3/mHqKBl2TDEczEJ/vkbYV1WobrVxaV6KKjzWjwJxxWbtMPWQTNaVMmUd5B88dmNEh9hw48mgExRoiOinG5RsjgavBjlgmDMALOQpl1ZNJucG1hWcUKJOczJwZCd9tpz77yg45dvpZM5VGY9FTdxKRO4rV2ssSwlvg9th41wwCuF5a1nRXhfhPf2Rb+X35S8ouHAi3djXfNEO2TKwuVrLm7wta6PXMvTdemVbw0ob5u1PZsKCchQWugH5MHF2GBzMrQ5JqZaduCcjWu0RQmGRuZFmUZOciFGo8Wby5GP+cbuHMsb9+9N967MRR70bhkZ6RR0Nc2/skq0B4nF5dfWLZ5L6sq/BHcGoCJnt1MPzySj7j3JVUGRKC+k=
  app: guarded-refuge-75246
  on:
    branch: main
